# Generated by Django 4.2.29 on 2026-03-09 01:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('warehouse_type', models.CharField(choices=[('main', 'Stock Principal'), ('technicien', 'Stock Technicien')], default='main', max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to=settings.AUTH_USER_MODEL, verbose_name='Technicien propriétaire')),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
                'ordering': ['warehouse_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('movement_type', models.CharField(choices=[('entree_fournisseur', 'Entrée fournisseur'), ('sortie_technicien', 'Sortie vers technicien'), ('retour_technicien', 'Retour technicien'), ('transfert_envoi', 'Transfert (envoi)'), ('transfert_reception', 'Transfert (réception)'), ('inventaire_plus', 'Régularisation inventaire (+)'), ('inventaire_moins', 'Régularisation inventaire (-)'), ('sortie_client', 'Sortie client (BL)'), ('autre', 'Autre')], max_length=30, verbose_name='Type de mouvement')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité')),
                ('direction', models.SmallIntegerField(choices=[(1, 'Entrée'), (-1, 'Sortie')], default=1, verbose_name='Direction')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence document')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product', verbose_name='Produit')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.warehouse', verbose_name='Entrepôt')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['warehouse', 'product'], name='stock_stock_warehou_6a193c_idx'), models.Index(fields=['movement_type'], name='stock_stock_movemen_b002ed_idx'), models.Index(fields=['created_at'], name='stock_stock_created_69d383_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantité')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='products.product', verbose_name='Produit')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='stock.warehouse', verbose_name='Entrepôt')),
            ],
            options={
                'verbose_name': 'Solde stock',
                'verbose_name_plural': 'Soldes stock',
                'ordering': ['product__designation'],
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
