# Generated by Django 4.2.29 on 2026-03-09 01:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Numéro')),
                ('delivery_date', models.DateField(verbose_name='Date BL')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('valide', 'Validé'), ('facture', 'Facturé')], default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'BL Client',
                'verbose_name_plural': 'BL Clients',
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Numéro')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Date livraison')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('valide', 'Validé'), ('en_transit', 'En transit'), ('recu', 'Reçu'), ('annule', 'Annulé')], default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technicien'}, on_delete=django.db.models.deletion.PROTECT, related_name='received_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Technicien destinataire')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'BL Interne',
                'verbose_name_plural': 'BL Internes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Numéro')),
                ('invoice_date', models.DateField(verbose_name='Date facture')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='suppliers.supplier', verbose_name='Fournisseur')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Facture fournisseur',
                'verbose_name_plural': 'Factures fournisseur',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantité')),
                ('unit_price_ht', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire HT')),
                ('total_price_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total HT')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='deliveries.supplierinvoice', verbose_name='Facture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne facture',
                'verbose_name_plural': 'Lignes facture',
            },
        ),
        migrations.CreateModel(
            name='InternalDeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantité')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='deliveries.internaldelivery', verbose_name='BL')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_delivery_lines', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne BL interne',
                'verbose_name_plural': 'Lignes BL internes',
            },
        ),
        migrations.CreateModel(
            name='CustomerDeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantité')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='deliveries.customerdelivery', verbose_name='BL')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_delivery_lines', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne BL client',
                'verbose_name_plural': 'Lignes BL client',
            },
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['status'], name='deliveries__status_aca254_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['supplier'], name='deliveries__supplie_f86780_idx'),
        ),
        migrations.AddIndex(
            model_name='internaldelivery',
            index=models.Index(fields=['status'], name='deliveries__status_b3bf6c_idx'),
        ),
        migrations.AddIndex(
            model_name='internaldelivery',
            index=models.Index(fields=['technician'], name='deliveries__technic_a39478_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdelivery',
            index=models.Index(fields=['status'], name='deliveries__status_d1af2d_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdelivery',
            index=models.Index(fields=['technician'], name='deliveries__technic_6ac83f_idx'),
        ),
        migrations.AddIndex(
            model_name='customerdelivery',
            index=models.Index(fields=['client'], name='deliveries__client__198cdb_idx'),
        ),
    ]
