# Generated by Django 4.2.29 on 2026-03-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdelivery',
            name='intervention_details',
            field=models.TextField(blank=True, verbose_name='Détails intervention'),
        ),
        migrations.AddField(
            model_name='customerdelivery',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Ordre client'),
        ),
    ]
